### ISSUE TITLE
Does NVIDIA have plan to open source HPCG code in older version of containers?

### ISSUE THREAD

**Issue by qizhi45** [NVIDIA/nvidia-hpcg#1]
Hello, Mohammad Almasri and nikita-shustrov.

Thanks for your contribution to the nvidia-hpcg project, the open source code helped me better understand how NVIDIA uses cuSPARSE and cuBLAS to help HPCG improve performance.

My understanding is that the HPCG binary in the latest version of the container (nvcr.io/nvidia/hpc-benchmarks:24.03) is compiled by current code, if I'm wrong, please correct me.

Limited by environment, I can only use older version of container (nvcr.io/nvidia/hpc-benchmarks:21.4-hpcg) for testing, It uses many self-implemented kernels, such as **SYMGS21_C1_kernel**, **SYMGS21_C2_kernel**, **SYMGS21_C3_kernel**,etc. I am confused as to why there are so many different kernel functions compared to the original HPCG code and current nvidia-hpcg code. So I want to know if NVIDIA has plans to open source the old version of HPCG code as a branch later.

Any response will help me a lot, thank you.

**Comment by nikita-shustrov** [comment]
Hello @qizhi45, 

Current codes of HPCG (https://github.com/NVIDIA/nvidia-hpcg/releases/tag/24.06) is used in NVIDIA HPC-Benchmarks container: nvcr.io/nvidia/hpc-benchmarks:24.06

The container nvcr.io/nvidia/hpc-benchmarks:24.03 contains older version of HPCG implementation.

**Comment by qizhi45** [comment]
> Hello @qizhi45,
> 
> Current codes of HPCG (https://github.com/NVIDIA/nvidia-hpcg/releases/tag/24.06) is used in NVIDIA HPC-Benchmarks container: nvcr.io/nvidia/hpc-benchmarks:24.06
> 
> The container nvcr.io/nvidia/hpc-benchmarks:24.03 contains older version of HPCG implementation.

OK, I get it, Thanks for your reply.
So are there plans to open source the old versions? I saw from nsight-system that hpcg (21.4-hpcg) and hpcg (24.03) call completely different CUDA kernel functions to implement SYMGS, while HPCG (24.06) only calls the CUSPARSE library. 
Excuse me for that, I am just curious about the implementation of the CUDA kernel functions of HPCG 21.4 and 24.03. It may involve business secrets of nvidia.

**Comment by nikita-shustrov** [comment]
Hello @qizhi45, 

At this moment, there aren't any plans to open source other HPCG versions.

**Comment by qizhi45** [comment]
OK, I get it. Thanks for your reply.
